// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission5.Models;

namespace mission5.Migrations
{
    [DbContext(typeof(AddMovieContext))]
    partial class AddMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission5.Models.AddMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Comedy",
                            Director = "Frank Coraci",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Waterboy",
                            Year = (short)1998
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Comedy",
                            Director = "David Dobkin",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Eurovision Song Contest: The Story of Fire Saga",
                            Year = (short)2020
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Action",
                            Director = "Zack Snyder",
                            Edited = false,
                            Rating = "R",
                            Title = "300",
                            Year = (short)2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
